### ISSUE TITLE
Docker Instance Non-Responsive

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2854]
I'm attempting to build a docker image and have it connect to my existing MySQL database.  I did a git clone and, using the below config, the build appears to succeed, but when I try to access the application, I get no response.  The docker and apache logs are empty in terms of showing any connection attempts.  I am very green when it comes to docker, so I have no idea if I am doing something wrong.
```
version: '3'
services:
  phpmyfaq:
    build: .
    restart: always
    stdin_open: true
    environment:
      - PMF_DB_HOST=MYSQL_FQDN
      - PMF_DB_NAME=DB
      - PMF_DB_USER=User@IP
      - PMF_DB_PASS=Password
      - PMF_DISABLE_HTACCESS=""
      - PMF_TIMEZONE="America/Chicago"
      - PMF_ENABLE_UPLOADS="On"
      - PMF_MEMORY_LIMIT="2048M" # only for development
      - PHP_LOG_ERRORS="On"
      - PHP_ERROR_REPORTING="E_ALL & E_DEPRECATED & E_STRICT" # Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
    ports:
      - '8084:80'
    volumes:
      - ./phpmyfaq:/var/www/html
    depends_on:
      - pnpm

  pnpm:
    image: node:20-alpine
    restart: 'no'
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm build"
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - composer

  composer:
    image: composer:latest
    restart: 'no'
    command: composer install --verbose --ignore-platform-reqs
    stdin_open: true
    tty: true
    volumes:
      - .:/app
```
